/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantalla;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pablo
 */
public class PantallaTipoTuberia extends javax.swing.JFrame {

    private PantallaSaltoBruto pSB;
    private DefaultTableModel modeloTabla;
    private String[] tipoMaterial=new String[]{"Asbestos-cement (new)",
                                        "Copper and Brass",
                                        "Sanitation brick",
                                        "Cast iron, new",
                                        "Cast iron, 10 years old",
                                        "Cast iron, 20 years old",
                                        "Cast iron, 30 years old",
                                        "Concrete, smooth finish",
                                        "Concrete, common finish",
                                        "Galvanized steel (new and old)",
                                        "New riveted steel",
                                        "Old riveted steel",
                                        "PVC",
                                        "PE",
                                        "Lead",
                                        "Aluminum",};
     
    /**
     * Creates new form PantallaTipoTuberia
     */
    public PantallaTipoTuberia(PantallaSaltoBruto pSB) {
        initComponents();
        //Le doy forma a la tabla
        modeloTabla=new DefaultTableModel();
        dibujarTabla();
        rellenarTabla();
        
        this.pSB=pSB;
        
    }
    
    public void pedirCoeficienteMaterial(){
        this.setVisible(true);
        pSB.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTipoTuberia = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaTipoTuberia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaTipoTuberia);

        jButton1.setText("Seleccionar material");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int filaTabla=tablaTipoTuberia.getSelectedRow();
       if(filaTabla==-1)
           JOptionPane.showMessageDialog(null,"Select a material");
       else{
           String[] coeficienteMaterial=new String[]{"135","130","100","130","110","94","82","130","120","125","110","85","140","150","135","130",};
           
           String c=coeficienteMaterial[filaTabla];
           String n=tipoMaterial[filaTabla];
           pSB.recogerCoeficienteMaterial(Integer.parseInt(c),n);//mandamos el coeficiente a la pantallaSaltaBruto
           this.setVisible(false);
           pSB.setVisible(true);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        this.pSB.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaTipoTuberia;
    // End of variables declaration//GEN-END:variables

    private void dibujarTabla() {
        tablaTipoTuberia.setModel(modeloTabla);
        //Le ponemos nombre a las columnas
        String[] columnasTablas={"Materials"/*,"Coeficiente de Hazem-Williams"*/};
        modeloTabla.setColumnIdentifiers(columnasTablas);
        //Para no permitir el redimensionamiento por el raton
        tablaTipoTuberia.getTableHeader().setReorderingAllowed(false);
        //Fijamos el ancho de cada columna
        tablaTipoTuberia.getColumnModel().getColumn(0).setPreferredWidth(200);
        //tablaTipoTuberia.getColumnModel().getColumn(1).setPreferredWidth(500);
        
        
    }

    private void rellenarTabla() {
    
        /*String[] tipoMaterial=new String[]{"Asbesto-cemento (nuevo)","Cobre y Latón","Ladrillo de saneamiento","Hierro fundido, nuevo","Hierro fundido, 10 años de edad",
            "Hierro fundido, 20 años de edad","Hierro fundido, 30 años de edad","Concreto, acabado liso","Concreto, acabado común","Acero galvanizado(nuevo y usado)","Acero remachado nuevo",
            "Acero remachado usado","PVC","PE","Plomo","Aluminio"};*/
        
        
        Object[] columna = new Object[2];
        for (int i = 0; i < 16; i++) {
            columna[0]=tipoMaterial[i];
            modeloTabla.addRow(columna);
        }
    }
}
