/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pantalla;

import Aplicacion.Figura;
import Aplicacion.Operaciones;
import Aplicacion.Punto;
import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.text.DecimalFormat;

/**
 *
 * @author pablo
 */
public class PantallaSaltoBruto extends javax.swing.JFrame {

    private Figura PATs1;
    private Figura PATs2;
    private Figura TURGO;
    private Figura PELTON;
    private Figura FRANCIS;
    private Figura BANKI;
    private Figura KAPLAN;
    private boolean[] turbinas;//True si el punto esta en el rango de la tuberia
    private String[] nombreTurbina;
    private float P;
    private PantallaTipoTuberia pTT;
    private int coeficienteMaterial;
    private String nombreMaterial;
    private Operaciones oper;
    private DecimalFormat df;
    private PantallaSaltoNeto sn;

    /**
     * Creates new form Pantalla
     */
    public PantallaSaltoBruto(PantallaSaltoNeto sn) {
        initComponents();
        //Definicion de las figuras
        Punto[] pPATs1 = {new Punto(0.004, 40.0), new Punto(0.01, 4.0), new Punto(0.025, 17.0), new Punto(18.0, 17.0), new Punto(0.5, 550),
            new Punto(0.06, 550.0), new Punto(0.06, 50), new Punto(0.02, 160.0), new Punto(0.01, 160.0), new Punto(0.004, 400.0)};

        Punto[] pPATs2 = {new Punto(0.09, 10.1), new Punto(0.35, 2.9), new Punto(0.49, 2.9), new Punto(0.68, 1.9), new Punto(8.1, 1.9), new Punto(1.81, 10.1)};
        Punto[] pTURGO = {new Punto(0.01, 200), new Punto(0.01, 25), new Punto(10, 25), new Punto(10, 50), new Punto(2, 250), new Punto(0.02, 250)};
        Punto[] pPELTON = {new Punto(0.01, 200), new Punto(0.01, 21), new Punto(0.3, 18), new Punto(0.5, 70), new Punto(5, 500), new Punto(2.8, 1000), new Punto(0.03, 1000)};
        Punto[] pFRANCIS = {new Punto(0.09, 60),/*punto guia*/ new Punto(0.2, 28),/*punto guia*/ new Punto(0.6, 8), new Punto(1.4, 4), new Punto(5, 4), new Punto(28, 90), new Punto(5, 500), new Punto(0.2, 500)};
        Punto[] pBANKI = {new Punto(0.004, 35), new Punto(0.004, 18), new Punto(0.007, 10), new Punto(0.02, 10), new Punto(0.1, 2), new Punto(0.8, 5), new Punto(10, 5), new Punto(9, 12), new Punto(0.5, 200), new Punto(0.2, 300), new Punto(0.04, 300), new Punto(0.01, 200), new Punto(0.01, 35)};
        Punto[] pKAPLAN = {new Punto(0.01, 22), new Punto(0.01, 3), new Punto(0.7, 3), new Punto(1, 2), new Punto(40, 2), new Punto(80, 6), new Punto(80, 15), new Punto(18, 60), new Punto(5, 60)};

        PATs1 = new Figura(pPATs1);
        PATs2 = new Figura(pPATs2);
        TURGO = new Figura(pTURGO);
        PELTON = new Figura(pPELTON);
        FRANCIS = new Figura(pFRANCIS);
        BANKI = new Figura(pBANKI);
        KAPLAN = new Figura(pKAPLAN);

        nombreTurbina = new String[]{"PATs", "TURGO", "PELTON", "FRANCIS", "BANKI", "KAPLAN", "Not one"};
        P = -1;
        pTT = new PantallaTipoTuberia(this);
        coeficienteMaterial = -1;
        oper = new Operaciones();
        df=new DecimalFormat("#.00");//esto es para que solo se muestre 2 decimales
        this.sn=sn;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Caudal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Analizar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        hAnuales = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        iHoras = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tuberiasDisponibles = new javax.swing.JTextArea();
        pAnual = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        saltoBruto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        dTuberia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lTuberia = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tablaTuberias = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        saltoNeto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        PipeType = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setText("m");

        jLabel3.setText("Flow rate");

        jLabel4.setText("m^3/s");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N

        jLabel6.setText("Available turbines");

        Analizar.setBackground(new java.awt.Color(255, 255, 255));
        Analizar.setText("Calculate");
        Analizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalizarActionPerformed(evt);
            }
        });

        jLabel8.setText("Annual generated power");

        jLabel11.setText("Daily hours of operation");

        jLabel13.setText("h");

        iHoras.setBackground(new java.awt.Color(255, 255, 255));
        iHoras.setText("Enter hours");
        iHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iHorasActionPerformed(evt);
            }
        });

        tuberiasDisponibles.setEditable(false);
        tuberiasDisponibles.setColumns(10);
        tuberiasDisponibles.setRows(2);
        jScrollPane2.setViewportView(tuberiasDisponibles);

        pAnual.setEditable(false);
        pAnual.setBackground(new java.awt.Color(200, 200, 200));
        pAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pAnualActionPerformed(evt);
            }
        });

        jLabel7.setText("Required energy height");

        jLabel1.setText("Pipe diameter");

        jLabel10.setText("Pipe lenght");

        jLabel17.setText("m");

        jLabel18.setText("m");

        tablaTuberias.setBackground(new java.awt.Color(255, 255, 255));
        tablaTuberias.setText("To select pipe type");
        tablaTuberias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablaTuberiasActionPerformed(evt);
            }
        });

        jLabel16.setText("Net energy height");

        saltoNeto.setEditable(false);
        saltoNeto.setBackground(new java.awt.Color(200, 200, 200));
        saltoNeto.setToolTipText("");
        saltoNeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saltoNetoActionPerformed(evt);
            }
        });

        jButton1.setText("Net energy height");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setText("Required energy height");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grafica/Graficas.jpeg"))); // NOI18N

        PipeType.setText("Pipe type:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(saltoNeto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel10)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(saltoBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel2))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(dTuberia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(lTuberia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel18)
                                                            .addComponent(jLabel17)))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(89, 89, 89)
                                                .addComponent(Caudal, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel4))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(40, 40, 40)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(iHoras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(hAnuales, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGap(18, 18, 18)
                                                            .addComponent(jLabel13)))))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(PipeType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(tablaTuberias, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(88, 88, 88)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addComponent(pAnual, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(Analizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel5)
                .addContainerGap(778, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(saltoBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dTuberia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lTuberia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tablaTuberias)
                        .addGap(6, 6, 6)
                        .addComponent(PipeType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(saltoNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Caudal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(Analizar)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hAnuales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addComponent(iHoras)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(pAnual, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalizarActionPerformed
        /////Boton Analizar/////
        try{
        this.ponerCuadrosBlancos();
        if (this.saltoBruto.getText().equals("") || this.Caudal.getText().equals("") || this.dTuberia.getText().equals("") || this.lTuberia.getText().equals("") || coeficienteMaterial == -1) {
            JOptionPane.showMessageDialog(null, "Enter all data");
            if(this.saltoBruto.getText().equals("")) this.saltoBruto.setBackground(Color.red);
            if(this.lTuberia.getText().equals("")) this.lTuberia.setBackground(Color.red);
            if(this.dTuberia.getText().equals("")) this.dTuberia.setBackground(Color.red);
            if(this.Caudal.getText().equals("")) this.Caudal.setBackground(Color.red);
            if(this.coeficienteMaterial==-1) this.tablaTuberias.setBackground(Color.red);
        } else {
            float sb = Float.parseFloat(this.saltoBruto.getText());
            float caudal = Float.parseFloat(this.Caudal.getText());
            float diametro = Float.parseFloat(this.dTuberia.getText());
            float longitud = Float.parseFloat(this.lTuberia.getText());
            float sn = oper.calcularSaltoNeto(sb, caudal, diametro, longitud, coeficienteMaterial);
            this.saltoNeto.setText(df.format(sn).toString()+ " m");
            Punto p = new Punto(caudal, sn);
            turbinas = new boolean[7];//reseteo las tuberias

            calcularTuberias(p);
            P = oper.calcularPotencia(p);
            mostrarTueberias();
            this.pAnual.setText(null);

        }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "The data must be numeric");
        }

    }//GEN-LAST:event_AnalizarActionPerformed

    private void iHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iHorasActionPerformed
        ponerCuadrosBlancos();
        if (this.hAnuales.getText().equals("")) {
            this.hAnuales.setBackground(Color.red);
            JOptionPane.showMessageDialog(null, "Enter the daily hours of operation");
        } else {
            float horas = Float.parseFloat(this.hAnuales.getText());
            if (horas > 24 || horas < 0) {
                this.hAnuales.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "One day only has 24 hours");
            } else {
                if (P == -1) {
                    this.Analizar.setBackground(Color.red);
                    JOptionPane.showMessageDialog(null, "Analyze the data first");
                } else {
                    this.pAnual.setText(null);
                    if (this.turbinas[turbinas.length - 1] == true) {
                        this.pAnual.setText("N");
                    } else {
                        //potenciaAnual=horasDiarias*diasDelAño*Potencai
                        Float PA = (float) (horas * 365 * P) / 1000;
                        if(PA>=1)
                            this.pAnual.setText(df.format(PA).toString() + "  " + "MW");
                        else
                             this.pAnual.setText("0"+df.format(PA).toString() + "  " + "MW");
                            
                    }
                }
            }
        }
    }//GEN-LAST:event_iHorasActionPerformed

    private void tablaTuberiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablaTuberiasActionPerformed
        pTT.pedirCoeficienteMaterial();//activamos la pantalla de la tabla

    }//GEN-LAST:event_tablaTuberiasActionPerformed

    private void saltoNetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saltoNetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saltoNetoActionPerformed

    private void pAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pAnualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pAnualActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        sn.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    //
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Analizar;
    private javax.swing.JTextField Caudal;
    private javax.swing.JLabel PipeType;
    private javax.swing.JTextField dTuberia;
    private javax.swing.JTextField hAnuales;
    private javax.swing.JButton iHoras;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lTuberia;
    private javax.swing.JTextField pAnual;
    private javax.swing.JTextField saltoBruto;
    private javax.swing.JTextField saltoNeto;
    private javax.swing.JButton tablaTuberias;
    private javax.swing.JTextArea tuberiasDisponibles;
    // End of variables declaration//GEN-END:variables

    private void calcularTuberias(Punto p) {
        int cont = 0;
        if (PATs1.dentro(p)) {
            turbinas[0] = true;
            cont++;
        }
        if (PATs2.dentro(p)) {
            turbinas[0] = true;
            cont++;
        }
        if (TURGO.dentro(p)) {
            turbinas[1] = true;
            cont++;
        }
        if (PELTON.dentro(p)) {
            turbinas[2] = true;
            cont++;
        }
        if (FRANCIS.dentro(p)) {
            turbinas[3] = true;
            cont++;
        }
        if (BANKI.dentro(p)) {
            turbinas[4] = true;
            cont++;
        }
        if (KAPLAN.dentro(p)) {
            turbinas[5] = true;
            cont++;
        }

        if (cont == 0) {
            turbinas[6] = true;//esta tuberia dice si no hay ninguna disponible
        }
    }

    private void mostrarTueberias() {
        //Mostraremos las tuberias y al lado la potencia que tiene

        //Esto es para cambiar las unidades
        String[] unidad = new String[]{"kW", "MW"};
        int sUnidad = 0;
        float auxP = P;
        if (P >= 1000) {
            auxP = P / 1000;
            sUnidad = 1;
        } else if (P < 1) {
            auxP = P * 1000;
            sUnidad = 2;
        }
        //Vamos a escribir las tuberias con la potencia al lado
        String mensaje = "";
        tuberiasDisponibles.removeAll();
        for (int i = 0; i < turbinas.length; i++) {
            if (turbinas[i] == true) {
                if (i != turbinas.length - 1) {
                    mensaje = mensaje + nombreTurbina[i] + " of " + auxP + " " + unidad[sUnidad] + "\n";
                } else//Si es la posicion de ninguna tuberia no se pone la potencia
                {
                    mensaje = nombreTurbina[i];
                }
            }
        }

        tuberiasDisponibles.setText(mensaje);

    }

    public void recogerCoeficienteMaterial(int coeficiente, String nombre) {
        this.coeficienteMaterial = coeficiente;
        this.nombreMaterial = nombre;
        
        this.PipeType.setText("Pipe type: "+ nombre);

    }
    
    private void ponerCuadrosBlancos() {
        this.dTuberia.setBackground(Color.white);
        this.lTuberia.setBackground(Color.white);
        this.saltoBruto.setBackground(Color.white);
        this.Caudal.setBackground(Color.white);
        this.hAnuales.setBackground(Color.white);
        this.tablaTuberias.setBackground(Color.white);
        this.Analizar.setBackground(Color.white);
    }

}
